### ISSUE TITLE
update because discord has been updated

### ISSUE THREAD

**Issue by bianvigano** [Zeptosec/ThermostoreFront#10]
https://cdn.discordapp.com/attachments/1184547360173465680/1205762718359887872/blob <can be used for the new one>
"This content is no longer available."

now there is parmeder
"ex": when will the link expire, "hm": file hash of the link, "is": there is a connection with "hm"

for example: ex=65d98d0a&is=65c7180a&hm=79027d47a64671ef8a312119b26b8142a908597f26ff0f8fa10b88d54ec3ecc9&

**Comment by Zeptosec** [comment]
This problem should be fixed.
