### ISSUE TITLE
Cannot access Discord Problem

### ISSUE THREAD

**Issue by bianvigano** [Zeptosec/ThermostoreFront#23]
**Describe the bug**
When attempting to access the URL https://example.com/download/balbal/balbal, an error occurs, and the page does not load as expected.

**Screenshots**
Please see the attached screenshots for reference:
![Screenshot from 2024-12-04 13-30-31](https://github.com/user-attachments/assets/146cab79-0bee-4605-a348-620893e62152)

![Workspace 1_001](https://github.com/user-attachments/assets/a003c371-6d43-4e62-bb73-d594b84cb2fc)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20
 - Browser: chrome

**Comment by Zeptosec** [comment]
https://github.com/Zeptosec/Thermastore/commit/4ec673655c69be2b576e70c7d2c0c9961be19454 and https://github.com/Zeptosec/Streamer/commit/ba362dd5e8e57ff036751857f05bd619da1d7782
These commits should fix the problem.
