### ISSUE TITLE
how to fix it?

### ISSUE THREAD

**Issue by bianvigano** [Zeptosec/ThermostoreFront#5]
![Screenshot from 2023-12-06 15-00-45](https://github.com/Zeptosec/Thermastore/assets/12135917/caf46277-596b-4556-a60d-c1d876da37d0)

Maybe it's because it's not completely clear about this database supabase

**Comment by Zeptosec** [comment]
Sorry, I haven't updated the database definitions in a while because supabase doesn't make it easy to export all definitions, functions and triggers. 

I've updated it enough to get it running and working. [supabase.ddl](/Zeptosec/Thermastore/blob/fix/database-config/supabase.ddl)

**Comment by bianvigano** [comment]
Already able to walk and work.

Thank you.

But why do we have to use a database from supabase.com.
Why not use SQL, SQLite, MySQL, and MongoDB databases?

**Comment by Zeptosec** [comment]
Supabase provided a better DX.
- It gives a free database (small but good enough for small projects).
- Handles auth.
- Has a decent library for retrieving/mutating user data - no need for API.

**Comment by bianvigano** [comment]
It looks like there's another bug, or perhaps another database problem.

So, the problem is that when I try to log in with another account, the contents of 'myfiles' are the same in that account.
It should be that different accounts have different 'myfiles.' this is the same

**Comment by Zeptosec** [comment]
It sounds like you need to setup [RLS](https://supabase.com/docs/guides/auth/row-level-security) on your tables.

I can provide you with some basic policies that should fix your problem:
https://github.com/Zeptosec/Thermastore/blob/3a93e66d51ccf4d41ca75f3330ebc6482a53b513/supabase.ddl#L200-L250
